name: My First CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1 - Get code
        uses: actions/checkout@v3

      - name: Step 2 - Inject DB URL
        run: echo "SPRING_DATASOURCE_URL=${{ secrets.DB_URL }}" >> $GITHUB_ENV

      - name: Step 3 - Print DB URL
        run: echo $SPRING_DATASOURCE_URL
