name: My First CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1 - Get code
        uses: actions/checkout@v3

      - name: Step 2 - Print message
        run: echo "CI/CD is working 🚀"
